set install_path=C:\Users\Mehmet Yigit Turali\anaconda3
set project_path=C:\Users\Mehmet Yigit Turali\PycharmProjects\ShellDatathon
call "%install_path%\Scripts\activate.bat"
echo Activating Environment...
conda activate sskproject
echo Going Project Directory...
cd "%project_path%"
echo Running the script...
streamlit run streamlit_app.py
echo APP...
timeout 5